/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TSAH;

import java.io.IOException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author TSAH
 */
public class addWordFrame extends javax.swing.JFrame {
    private int SeLan = 1;
    private HashMap mapEv;
    private HashMap mapVe;
    final static String FILE_PATH_ADDED_EV = "data/addedE_V.txt";
    final static String FILE_PATH_ADDED_VE = "data/addedV_E.txt";
    /**
     * Creates new form addWord
     */
    public addWordFrame(HashMap mapEv, HashMap mapVe) {
        initComponents();
        this.mapEv = mapEv;
        this.mapVe = mapVe;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfWord = new javax.swing.JTextField();
        tfMean = new javax.swing.JTextField();
        btAddWord = new javax.swing.JButton();
        cbSeLan = new javax.swing.JComboBox<>();
        btClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Từ cần thêm");

        jLabel2.setText("Nghĩa của từ");

        btAddWord.setText("Thêm");
        btAddWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddWordActionPerformed(evt);
            }
        });

        cbSeLan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En->Vi", "Vi->En" }));
        cbSeLan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSeLanItemStateChanged(evt);
            }
        });

        btClose.setText("Đóng");
        btClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfWord, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbSeLan, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btAddWord)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btClose))
                        .addComponent(tfMean, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btAddWord, btClose});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(cbSeLan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(tfMean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAddWord)
                    .addComponent(btClose))
                .addContainerGap(168, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddWordActionPerformed
        // TODO add your handling code here:
        String word = Std.StdStr(tfWord.getText());
        String mean = Std.StdStr(tfMean.getText());
        String str = word+"<html><font color='#cc0000'><b>"+mean+"</b></font></html>\r\n";
//        str = Std.StdStr(str);
        if(!("".equals(tfWord.getText())||"".equals(tfMean.getText()))){
            if(1 == SeLan){
                try {
                    if(mapEv.containsKey(word)){
                        JOptionPane.showMessageDialog(null, "Từ "+word+" đã có trong từ điển!", "Warning", JOptionPane.WARNING_MESSAGE);
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Bạn có chắc muốn thêm từ " + word, "Thêm từ", JOptionPane.INFORMATION_MESSAGE);
                        WriteData.WriteFile(FILE_PATH_ADDED_EV, str, true);
                        mapEv.put(word, "<html><font color='#cc0000'><b>"+mean+"</b></font></html>");
                    }
                } catch (IOException ex) {
                    Logger.getLogger(addWordFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                try {
                    if(mapVe.containsKey(word)){
                        JOptionPane.showMessageDialog(null, "Từ "+word+" đã có trong từ điển!", "Warning", JOptionPane.WARNING_MESSAGE);
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Bạn có chắc muốn thêm từ " + word, "Thêm từ", JOptionPane.INFORMATION_MESSAGE);
                        WriteData.WriteFile(FILE_PATH_ADDED_VE, str, true);
                        mapVe.put(word, "<html><font color='#cc0000'><b>"+mean+"</b></font></html>");
                    }
                    
                } catch (IOException ex) {
                    Logger.getLogger(addWordFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        tfWord.setText("");
        tfMean.setText("");
    }//GEN-LAST:event_btAddWordActionPerformed

    private void cbSeLanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSeLanItemStateChanged
        if("En->Vi".equals(cbSeLan.getSelectedItem().toString())){
            SeLan = 1;
        }
        else{
            SeLan = 2;
        }
        
    }//GEN-LAST:event_cbSeLanItemStateChanged

    private void btCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddWord;
    private javax.swing.JButton btClose;
    private javax.swing.JComboBox<String> cbSeLan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tfMean;
    private javax.swing.JTextField tfWord;
    // End of variables declaration//GEN-END:variables
}
