/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TSAH;

import java.io.IOException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author TSAH
 */
public class ShowListFrame extends javax.swing.JFrame {

    /**
     * Creates new form ShowListFrame
     */
    private HashMap mapEv;
    private HashMap mapVe;
    private int selectLanguage = 1;
    private DefaultListModel modelEv = new DefaultListModel();
    private DefaultListModel modelVe = new DefaultListModel();
    private HashMap<String, String> newMapEv;
    private HashMap<String, String> newMapVe;
    final static String FILE_PATH_ADDED_EV = "data/addedE_V.txt";
    final static String FILE_PATH_ADDED_VE = "data/addedV_E.txt";
    
    public ShowListFrame(HashMap mapEv, HashMap mapVe) {
        initComponents();
        jEditorMeanOfWord.setContentType("text/html");
        this.mapEv = mapEv;
        this.mapVe = mapVe;
        initData();
    }
    private void initData(){
        newMapEv = mapEv;
        newMapVe = mapVe;
        for(String key : newMapEv.keySet()){
            modelEv.addElement(key);
        }
        for(String key : newMapVe.keySet()){
            modelVe.addElement(key);
        }
        jListWord.setModel(modelEv);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListWord = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorMeanOfWord = new javax.swing.JEditorPane();
        btEdit = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        brClose = new javax.swing.JButton();
        cbSelectLanguage = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Danh sách từ đã thêm");

        jListWord.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListWordValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListWord);

        jScrollPane1.setViewportView(jEditorMeanOfWord);
        jEditorMeanOfWord.getAccessibleContext().setAccessibleDescription("text/html");

        btEdit.setText("Edit");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        btDelete.setText("Delete");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        brClose.setText("Close");
        brClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brCloseActionPerformed(evt);
            }
        });

        cbSelectLanguage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En->Vi", "Vi->En" }));
        cbSelectLanguage.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSelectLanguageItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(cbSelectLanguage, 0, 103, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btEdit)
                                .addGap(34, 34, 34)
                                .addComponent(btDelete)
                                .addGap(27, 27, 27)
                                .addComponent(brClose)))
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cbSelectLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btEdit)
                            .addComponent(btDelete)
                            .addComponent(brClose))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        try {
            String str = jEditorMeanOfWord.getText();
            String word = jListWord.getSelectedValue().toString();
            word = Std.StdStr(word);
            if("En->Vi".equals(cbSelectLanguage.getSelectedItem().toString())){
                mapEv.remove(word);
                mapEv.put(word, str);
                modelEv.clear();
                newMapEv = mapEv;
                for(String key : newMapEv.keySet()){
                    modelEv.addElement(key);
                }
                jListWord.setModel(modelEv);
            }
            else{
                mapVe.remove(word);
                mapVe.put(word, str);
                modelVe.clear();
                newMapVe = mapVe;
                for(String key : newMapVe.keySet()){
                    modelVe.addElement(key);
                }
                jListWord.setModel(modelVe);
            }
        } catch (Exception e) {
            System.out.println("Khong co tu");
        }
        
    }//GEN-LAST:event_btEditActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        // TODO add your handling code here:
        String word = jListWord.getSelectedValue().toString();
        if(null != word){
            word = Std.StdStr(word);
            if("En->Vi".equals(cbSelectLanguage.getSelectedItem().toString())){
                mapEv.remove(word);
                modelEv.clear();
                newMapEv = mapEv;
                for(String key : newMapEv.keySet()){
                    modelEv.addElement(key);
                }
                jListWord.setModel(modelEv);
            }
            else{
                mapVe.remove(word);
                modelVe.clear();
                newMapVe = mapVe;
                for(String key : newMapVe.keySet()){
                    modelVe.addElement(key);
                }
                jListWord.setModel(modelVe);
            }
            jEditorMeanOfWord.setText("");
        }
    }//GEN-LAST:event_btDeleteActionPerformed

    private void cbSelectLanguageItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSelectLanguageItemStateChanged
        // TODO add your handling code here:
        if("En->Vi".equals(cbSelectLanguage.getSelectedItem().toString())){
            jListWord.setModel(modelEv);
        }
        else{
            jListWord.setModel(modelVe);
        }
    }//GEN-LAST:event_cbSelectLanguageItemStateChanged

    private void brCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brCloseActionPerformed
        try {
            WriteData.WriteFile(FILE_PATH_ADDED_EV, "", false);
            WriteData.WriteFile(FILE_PATH_ADDED_VE, "", false);
            for(String key : newMapEv.keySet()){
                try {
                    WriteData.WriteFile(FILE_PATH_ADDED_EV, key+mapEv.get(key)+"\r\n", true);
                    System.out.println(key+mapVe.get(key)+"\r\n");
                } catch (IOException ex) {
                    WriteData.WriteFile(FILE_PATH_ADDED_EV, "", true);
                }
            }
            for(String key : newMapVe.keySet()){
                try {
                    WriteData.WriteFile(FILE_PATH_ADDED_VE, key+mapVe.get(key)+"\r\n", true);
                    System.out.println(key+mapVe.get(key)+"\r\n");
                } catch (IOException ex) {
                    WriteData.WriteFile(FILE_PATH_ADDED_VE, "", true);
                }
            }
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(ShowListFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_brCloseActionPerformed

    private void jListWordValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListWordValueChanged
        try {
            String word = jListWord.getSelectedValue().toString();
            word = Std.StdStr(word);
            if(null != word){
                if("En->Vi".equals(cbSelectLanguage.getSelectedItem().toString())){
                    jEditorMeanOfWord.setText(mapEv.get(word).toString());
                }
                else{
                    jEditorMeanOfWord.setText(mapVe.get(word).toString());
                }
            }
        } catch (Exception e) {
            System.out.print("Xay ra ngoai le");
        }
    }//GEN-LAST:event_jListWordValueChanged

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brClose;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btEdit;
    private javax.swing.JComboBox<String> cbSelectLanguage;
    private javax.swing.JEditorPane jEditorMeanOfWord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jListWord;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
